name: "postprocess"
backend: "python"
input [
  {
    name: "logits"
    data_type: TYPE_FP32  # Ensure the correct data type notation
    dims: [-1, 2]
  }
]
output [
  {
    name: "label"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "score"
    data_type: TYPE_FP32  # Ensure the correct data type notation
    dims: [1]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]

