name: "postprocess"
backend: "python"
input[
  {
   name:"logits",
   data_type: TYPE_FLOAT32,
   dims:[-1,1]
  }
]
output[
  {
   name:"label",
   data_type: TYPE_STRING,
   dims:[1]
  }
  {
    name:"score",
    data_type: TYPE_FLOAT32,
    dims:[1]
  }
]
