## Use model_transaction_policy to support decoupled inference and streaming 
name: "orpheus"
backend: "python"
model_transaction_policy {
  decoupled: True
}
max_batch_size: 0
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [-1]
  },
  {
    name: "speaker_id"
    data_type: TYPE_STRING
    dims: [-1] 
  }
]
output [
  {
    name: "audio"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "sampling_rate"
    data_type: TYPE_FP32
    dims:[1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]
