name: Build and Push Docker Image

on:
  push:
    paths:
      - 'capsules/arsat-customer-care/**'
      - '.github/workflows/docker-image.yml'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/fiveit-dev/arsat-customer-care:dev-0.0.0 capsules/arsat-customer-care

      - name: Push Docker Image
        run: |
          docker push ghcr.io/fiveit-dev/arsat-customer-care:dev-0.0.0
